- .travis.yml
- src/vdom.rs
I was not able to enable the tests on travis, but enabling the build let me catch a small error in one test.
A new PR will follow if I'll manage travis to run the tests too.
> ci: add minimal travis config (build --tests) + fix error in vdom

- .travis.yml
- Cargo.toml
- src/vdom.rs
- add firefox as addon
- cache cargo (allow failure on cargo install)
- disable windows because of https://travis-ci.org/naufraghi/seed/jobs/475998812#L630
> ci: Enable test with wasm-bindgen-test and wasm-pack

- src/vdom.rs
Modifying the app state from the outside
could be helpfull, eg.:
```rust
pub fn render() {
let app = seed::run(Model::default(), update, view, "app", None, None);
open_websockets(app);
}
fn open_websockets(state: seed::App<Msg, Model>) {
// setup websockets ...
let on_message = Box::new(move|ev: MessageEvent| {
let txt = ev.data().as_string().unwrap();
let json = : JsonMsg = serde_json::from_str(&text).unwrap();
state.update(Msg::Json(json));
});
}
```
> Return App from seed::run

- src/websys_bridge.rs
Using El::from_html wraps the created DOM node in a ```<span>```.
```
pub fn from_html(html: &str) -> Self {
let mut result = Self::empty(Tag::Span);
result.raw_html = true;
result.text = Some(html.into());
result
}
``` 
This was surprising and caused me some problems when porting some HTML which expected parent-child relationships to remain intact.
In the case that this was not intended this PR removes the ```<span>```, rendering only its child which is the node created from the raw_html string. 
If it was intended, would mind explaining the reasoning? 
Thank you.
> Do not wrap raw_html elements with a span

- examples/counter/src/lib.rs
- examples/server_interaction/src/lib.rs
- src/lib.rs
- src/vdom.rs
My rationale for the suggested changes follows.
In my app I have a few subcomponents, so the update function for my parent component looks something like this:
```rust
match message {
Msg::InnerComponent1(message) => {
let Model { inner1, inner2, inner3 } = model;
let upd = inner_module::update(message, inner1);
wrap_update(
upd,
|inner1| Model { inner1, inner2, inner3 },
|msg| Msg::InnerComponent1(msg),
)
}
}
```
where `wrap_update` is a helper function that matches the contents of the Update enum and converts the model part to the parent component's model using the first closure, and also converts the message part to the parent component's message type using the second closure.
Anyway, I have to unpack my Model and then put it back together so that I can pass the inner component's Model …
> &mut for Update + returning Futures from Update

- src/dom_types.rs
I think this is a pretty naive solution that wrapping the all the nested Listeners for the affected component function every time view() is called. If there was a lazy way to do this, so that the conversion only needs to happen when the listener is fired, this would be much lower overhead. 
I haven't tested this yet, but I imagine it could be used in some way like this:
```rust
struct Model {
data: String,
third_party: ThirdPartyModel
}
enum Msg {
UpdateData,
ThirdParty(ThirdPartyMsg)
}
impl From<ThirdPartyMsg> for Msg {
fn from(other: ThirdPartyMsg) -> Self {
Msg::ThirdParty(other)
}
}
fn update(msg: Msg, &mut model: Model) -> Update<Msg> {
match msg {
ThirdParty(tp_msg) => third_party_update(tp_msg, &mut model.third_party),
...
}
...
}
fn view(model: &Model) -> El<Msg> {
div![ …
```
> Support converting message types from other crates

- .travis.yml
- Makefile.toml
- README.md
- examples/counter/Makefile.toml
- examples/server_integration/Makefile.toml
- examples/server_interaction/Makefile.toml
- examples/todomvc/Makefile.toml
- examples/websocket/Makefile.toml
- examples/window_events/Makefile.toml
I found out that `wasm-pack build` builds in dev mode [by default](https://rustwasm.github.io/wasm-pack/book/commands/build.html#profile). So I've fixed it and written `*_release` tasks.
If dev mode is enough in CI, building will be 2x faster.
I've also added more badges into `README.md`.
> release tasks and readme badges

- examples/server_integration/client/src/example_a.rs
- examples/server_integration/client/src/example_b.rs
- examples/server_integration/client/src/example_c.rs
- examples/server_integration/client/src/example_d.rs
- src/shortcuts.rs
- New macro `empty!` - I think it's a little bit more readable than `seed::empty()` and more consistent with other DOM elements, so it should be clear on the first look that it represents an `El`.
- Todos could be resolved thanks to your correcting of root elements behavior (#119).
- Some typos fixed.
> resolved todos in server_integration examples, macro empty!

- Cargo.lock
- Cargo.toml
- Makefile.toml
- examples/animation_frame/Cargo.toml
- examples/counter/Cargo.toml
- examples/mathjax/Cargo.toml
- examples/orders/Cargo.toml
- examples/server_integration/Cargo.lock
- examples/server_integration/client/Cargo.toml
- examples/server_integration/server/Cargo.toml
- examples/server_integration/shared/Cargo.toml
- examples/server_interaction/Cargo.toml
- examples/server_interaction_detailed/Cargo.lock
- examples/server_interaction_detailed/Cargo.toml
- examples/server_interaction_detailed/me/Cargo.toml
- examples/server_interaction_detailed/reports/Cargo.toml
- examples/todomvc/Cargo.toml
- examples/update_from_js/Cargo.toml
- examples/websocket/Cargo.toml
- examples/window_events/Cargo.toml
#125 
Added tasks `verify` and `test_h_firefox`
---
I saw a few times this error while running `cargo make all`:
```
...
rust-lld: error: duplicate symbol: __wbindgen_describe___widl_f_resu
lt_DOMException
>>> defined in C:\Users\Martin\Desktop\hellweb\martinkavik_seed\targ
et\wasm32-unknown-unknown\debug\deps\libweb_sys-ad04f3cde63937fc.rlib(web_sys-
ad04f3cde63937fc.web_sys.6uvz5zel-cgu.0.rcgu.o)
>>> defined in C:\Users\Martin\Desktop\hellweb\martinkavik_seed\targ
et\wasm32-unknown-unknown\debug\deps\libweb_sys-2dea049ac97f1222.rlib(web_sys-
2dea049ac97f1222.web_sys.3c9d52pg-cgu.0.rcgu.o)
rust-lld: error: too many errors emitted, stopping now (use -error-l
imit=0 to see all errors)
error: aborting due to previous error
error: Could not compile `counter`.
```
There are some reported …
> new tasks: verify, test_h_firefox ; updated dependencies

- README.md
- examples/animation_frame/src/lib.rs
- examples/counter/src/lib.rs
- examples/orders/src/lib.rs
- examples/server_integration/client/src/lib.rs
- examples/server_interaction_detailed/reports/src/lib.rs
- examples/update_from_js/src/lib.rs
- src/css_units.rs
- src/dom_types.rs
- src/lib.rs
#127 
Start code review with `src/css_units.rs` - first look at the tests.
It's inspired by your comment https://github.com/David-OConnor/seed/issues/127#issuecomment-500087906.
Changes:
- Helpers for appending units implemented.
- `px` auto appending removed.
- All examples fixed and checked.
First impressions:
**unit!** 
- (+) Seems to be more consistent with other macros like `format!`.
- (+) Unit as suffix is more natural for reading (e.g. `unit!(width, px)`.
- (+) Is suitable for special units (e.g. `unit!(height, %)`) .
- (-) Is a relatively long expression because of macro name.
**px, vmin, ..**
- (+) Short.
- (+) Simple.
- (-) There can be name collisions.
- (-) A little bit less natural to read because of prefix notation (e.g. `px(150 + width)`.
- (-) A little bit awkward for …
> 127-css-units

- Cargo.lock
- Cargo.toml
- examples/animation_frame/Cargo.toml
- examples/counter/Cargo.toml
- examples/mathjax/Cargo.toml
- examples/orders/Cargo.toml
- examples/orders/src/lib.rs
- examples/server_integration/Cargo.lock
- examples/server_integration/client/Cargo.toml
- examples/server_integration/server/Cargo.toml
- examples/server_integration/shared/Cargo.toml
- examples/server_interaction/Cargo.toml
- examples/todomvc/Cargo.toml
- examples/todomvc/src/lib.rs
- examples/update_from_js/Cargo.toml
- examples/update_from_js/src/lib.rs
- examples/websocket/Cargo.toml
- examples/websocket/src/client.rs
- examples/websocket/src/json.rs
- examples/websocket/src/server.rs
- src/dom_types.rs
- src/gloo_timers/future.rs
- src/gloo_timers/mod.rs
- src/lib.rs
- src/shortcuts.rs
- src/storage.rs
Motivation for this request was errors like this:
```
...
rust-lld: error: duplicate symbol: __wbindgen_describe___widl_f_resu
lt_DOMException
>>> defined in C:\Users\Martin\Desktop\hellweb\martinkavik_seed\targ
et\wasm32-unknown-unknown\debug\deps\libweb_sys-ad04f3cde63937fc.rlib(web_sys-
ad04f3cde63937fc.web_sys.6uvz5zel-cgu.0.rcgu.o)
>>> defined in C:\Users\Martin\Desktop\hellweb\martinkavik_seed\targ
et\wasm32-unknown-unknown\debug\deps\libweb_sys-2dea049ac97f1222.rlib(web_sys-
2dea049ac97f1222.web_sys.3c9d52pg-cgu.0.rcgu.o)
rust-lld: error: too many errors emitted, stopping now (use -error-l
imit=0 to see all errors)
error: aborting due to previous error
error: Could not compile `counter`.
```
This error is probably caused by fighting between linker / wasm-pack / caching (don't know …
> fix-macros-and-examples

- .travis.yml
- Makefile.toml
Changes:
- New task `publish_dry_run` - it should prevent _"gloo_timers accidents"_.
- `publish_dry_run` integrated into task `verify`.
- New task `verify_only` - same like `verify` but doesn't make changes, intended to use in CI.
- Updated `.travis.yml` - uses `verify_only`.
I recommend to allow only merge branches to `master` with successful build (if you haven't set it up yet or it isn't GitHub default behavior). Because I've changed `.travis.yml` and I don't know if it pass on the first try. And button like GitLab's one "Merge when pipeline succeeds" is nice if GitHub has it.
---
I don't know how much is releasing annoying for you / error prone - but I saw some `cargo make` [flows](https://github.com/sagiegurari/cargo-make#predefined-flows) which should help with it or we can write …
> tasks publish_dry_run and verify_only

- examples/orders/src/lib.rs
- examples/todomvc/src/lib.rs
- examples/update_from_js/src/lib.rs
- src/shortcuts.rs
#142 
Soo..  we can use commas, semicolons and nothing (whitespace) as separator.. see examples, weird but seems to work.
> 142-comma-for-attrs-and-style

- src/shortcuts.rs
New macro **`plain!`**. It cannot be `text!` like in Elm because of conflict with svg `text!`.
Real-world example:
```rust
fn view_navbar_link<Ms>(&self, route: &route::Route, link_content: impl UpdateEl<El<Ms>>) -> El<Ms> {
a![
attrs!{At::Href => route.to_string()},
link_content
]
}
//...
self.view_navbar_link(
&route::Route::NewArticle,
vec![
i![
class!["ion-compose"]
],
plain!("\u{00A0}New Post")
]
),
```
> macro plain!

- examples/server_integration/client/src/example_a.rs
- examples/server_integration/client/src/example_b.rs
- examples/server_integration/client/src/example_c.rs
- examples/server_integration/client/src/example_d.rs
- examples/server_interaction/src/lib.rs
- src/dom_types.rs
- src/fetch.rs
- src/shortcuts.rs
Changes (all non-breaking):
- `fetch.rs` - I found out that we don't want to know response, only response data and fail reason in the most cases. You can see how new methods work in practice in `server_interaction` example.
- type `ResponseDataResult<T>`
- method `response_data()`
- method `fetch_string_data()`
- method `fetch_json_data()`
- refactored examples `server_integration` and `server_interaction`
- empty strings are filtered out in `add_multiple` - see modified test `src/dom_types.rs:1638`. The main reason is conditions in `class!` macro - e.g.: 
```rust
class![ "my_class", if something { "my_other_class" } else { "" }  ]
```
---
I don't know if it's possible but another option how to handle conditional classes would be:
```rust
class!["my_class", something => "my_other_class"] …
```
> Fetch - response_data, fetch_string_data, fetch_json_data

- src/shortcuts.rs
This PR fixes my bug in `class!`. 
It was a very nice bug - I forgot to add `return` into closure so `return` leaks to code that used macro. All tests were passing because test is marked as `passed` if it returns `()`.. I don't know how to prevent it without some weird boilerplate.
P.S. Nice contrib. guide!
> fix: missing closure in class!

- src/vdom.rs
- src/websys_bridge.rs
`Websys_bridge` shim for processing attribute `disabled` was only preventing from creating this attr when `attrs!{ At::Disabled => false }` but it didn't remove it when it was already present in DOM. See test in code.
> fix removing attribute `disabled`

- src/dom_types.rs
- src/lib.rs
- src/vdom.rs
#166 
I don't know how to write a proper test for this, because only scenario when it fails for me is:
> I'm able to pretty reliable reproduce it in realworld example:
> 1. Open http://localhost:8000/settings (you have to be logged in)
> 2. Press F5 and immediately click on New Post => panic Missing child el_ws
But the main problem was trying to get DOM node for `empty` element.
So I've added simple conditions into patch algorithm and custom tag `Empty` so it will be at least easier to debug it next time.
---
@David-OConnor 
I think (and if I remember correctly someone's already suggested it) that we should refactor in the future `El` into something like `Node` enum with variants like `Text`, `Empty`, `Html` `Svg`, etc. ; because `Option`s and `bool`s are often time bombs.
@flosse Could …
> 166-patch-empty-element

- examples/animation_frame/src/lib.rs
- examples/websocket/src/client.rs
- src/dom_types.rs
- src/shortcuts.rs
- src/websys_bridge.rs
Changes
- `&str` or `String` in parameters replaced with  `impl Into<Cow<'static, str>>` so it should be a little bit more flexible and efficient
- `impl ToString` and `pub fn ToString` replaced with `impl Display` (see description in https://doc.rust-lang.org/std/string/trait.ToString.html)
- `El<Msg>` replaced with `Node<Msg>` so all examples are buildable
Notes
- I think we can make `Cow<'static, str>` even more efficient once `specialization` is stable.
> Cow instead of String

- Cargo.toml
- examples/server_integration/client/src/example_a.rs
- examples/server_integration/client/src/example_c.rs
- examples/server_integration/client/src/example_e.rs
- examples/server_integration/client/src/lib.rs
- examples/server_integration/server/src/main.rs
- examples/todomvc/src/lib.rs
- src/dom_types.rs
- src/dom_types/values.rs
- src/lib.rs
- src/patch.rs
- src/shortcuts.rs
- src/util.rs
- src/vdom.rs
- src/websys_bridge.rs
https://github.com/David-OConnor/seed/issues/182
- First look at the file `src/dom_types/values.rs`.
- It's the core of the new API with comments and examples.
- Then look at the a new example `examples/server_integration/client/src/example_e.rs`.
- New API is tested here + I want to use it for testing issues with jumping cursor and closures.
- Then look at the `src/websys_bridge.rs` - find comment `// @TODO handle also other Auto* attributes?`.
- I tried to fix issues with auto-focusing here.
- You can try it with `cargo make start server_integration` - the first input should be focused.
- Breaking changes:
- You need to call method `as_at_value` for `bool` attributes (e.g. `At::Disabled => false.as_at_value()`), otherwise it would render as `disabled="false"`.
Thanks for review!
P.S. …
> 182-conditional-attrs-styles

- examples/server_integration/client/src/example_e.rs
- src/dom_types.rs
- src/events.rs
- src/vdom.rs
https://github.com/David-OConnor/seed/issues/169
(It's based on PR https://github.com/David-OConnor/seed/pull/186 so code review makes sense after merge.)
Changes
- `MessageMapper`'s callback signature changed to `FnOnce`:
- `fn map_message(self, f: impl FnOnce(Ms) -> OtherMs + 'static + Clone)`
- Fixed implementation of `MessageMapper` for `Listener`:
- `message: None` => `message: self.message.map(f)`
- Event handlers in `events.rs` changed :
- `handler: impl FnOnce(web_sys::KeyboardEvent) -> Ms + 'static + Clone`
- Updated example `server_integration\client\src\example_e.rs` - it uses closure in `raw_ev`.
Breaking changes
- There shouldn't be any.
Notes
- There are many new `.clone()` calls, but I think that the most of them should be cheap (i.e. compiler should optimize it - if it …
> 169 map message handlers closures

- .travis.yml
There is probably a bug in chromedriver / its configuration in wasm-pack. See failed build in [travis](https://travis-ci.org/David-OConnor/seed/jobs/570685268) and comment in changed `.travis.yml`.
`cargo make test_h chrome` also stopped working on my computer.
> commented out chrome test

- examples/todomvc/src/lib.rs
- src/lib.rs
- src/routing.rs
- src/vdom.rs
I was attempting to load in `seed` from an endpoint other than `/`. After a while struggling with attempting to manually route using `web-sys`, I decided to simply provide an escape hatch by allowing routing to return an `Option`.
I hope that the usage is relatively intuitive, but if you return a `None`, routing will fail and fall back to the default operation. If a `Some` is returned, then routing will happen as per the original routing code.
Maybe this should be done a different way? But this was the simplest solution I could think of.
> Add escape hatch from custom routing.

- Cargo.lock
- Cargo.toml
- build.rs
- examples/drop/src/lib.rs
- examples/server_integration/Cargo.lock
- src/dom_types.rs
- src/lib.rs
- src/orders.rs
- src/patch.rs
- src/shortcuts.rs
- src/util.rs
- src/vdom.rs
- src/websys_bridge.rs
Changes
- `log` and `error` returns input, so we can use them as wrappers.
- `log`, `log!`, `error` and `error!` accepts non-`Debug` objects on `nightly` Rust. Why? You can write `log!(my_element);` somewhere in Seed and you don't have to add `Ms: Debug` on 1569 places in code.
- Fixed `Clone` implementation for `El` - yeah, we should take `todos` more seriously.. ; It fixes `Drop` example; A little bit breaking change, because `Msg` has to implement `Clone`. But if you use at least one event handler in your app, you already implemented it.
@David-OConnor Could you please test `log`, `error`, `log!` and `error!` on `stable` and `nightly` before merge? I'm not sure if I tested it properly and you'll maybe find out some problems which I don't see.
> Easier debugging, fixed El::Clone

- src/vdom.rs
Resolves #241 
I've removed `mount_el` because it's deprecated for a long time and I didn't want to add Webkit workaround to more places.
`document().query_selector("html")` is probably the least invasive / visible dummy call which works for me (iOS and desktop Safari 12.1.2).
> fix(mount): Webkit workaround,  remove mount_el

- examples/mathjax/src/lib.rs
- src/dom_types.rs
- src/shortcuts.rs
Changes
- `Tag::from` is more flexible and doesn't force to allocate memory for `String`. Non-standard tag is now transformed to `Tag::Custom(..)`.
- Macro `custom!` checks if you set tag. It panics when you forget.
- Super small change in `mathjax` example to demonstrate updated `Tag::from`.
Motivation
- I'm trying to convert Markdown files to HTML and replace `pre` with web components with syntax highlighting. It's impossible without this PR.
> Better custom el. support

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/routing.rs
- src/vdom.rs
Need to make `Url` parsing from string work with hash and search before merging; currently treats them as part of `path`.
> Added hashchange listener

- src/dom_types.rs
- src/events.rs
- src/lib.rs
- src/orders.rs
- src/patch.rs
- src/util.rs
- src/vdom.rs
- src/websys_bridge.rs
There was a change that could eliminate most of the times `Msg` needed to have the `Clone` bound.
> Remove the Clone bound from messages where possible.

- src/vdom.rs
- src/vdom/alias.rs
- src/vdom/builder.rs
> Move `AppBuilder` and a few type aliases into a separate file.

- src/websys_bridge.rs
A part of #235.
This is so that the conversion can be used without the other two branches and so that it is not wrapped in a Node.
> Extract conversion of `web_sys::El` into `El` from a method

- src/dom_types.rs
A part of #235.
Also adds a few simple convenience methods for `Node`
> Method for stripping out the websys node in vdom.

- src/vdom.rs
- src/websys_bridge.rs
Part of #235.
Forces `process_cmd_and_msg_queue` to occur after the `main_el_vdom` is initialized, making it consistent with all other calls of `process_cmd_and_msg_queue`.
Also removes an extra `Node` wrapping for calling `assign_ws_nodes_to_el` when bootstrapping the vdom.
> Tweak bootstrap order so that `main_el_vdom` is initialized first.

- examples/server_integration/Cargo.lock
- src/dom_types.rs
- src/dom_types/values.rs
- src/shortcuts.rs
- src/vdom.rs
PR for #268, please give extra review since this is my 1st PR :D
> Accept more types in style! macro

- examples/server_integration/Cargo.lock
- src/lib.rs
- src/vdom.rs
- src/vdom/builder.rs
The last part of #235.
- Allow Seed to take over the children of the mount. This can be useful for SSR. This is partially related to #232, which is also related to #223.
- Warns of possibly questionable behavior when attempting to accomplish the above maneuver as it is now (see the doc comment for `takeover_mount` in `AppBuilder`). Due to this behavior and backwards compatibility, it is currently an opt in functionality.
> Add parameter for specifying what to do with elements that already exist within the mount.

- CHANGELOG.md
- README.md
- examples/animation_frame/src/lib.rs
- examples/counter/src/lib.rs
- examples/drop/src/lib.rs
- examples/mathjax/src/lib.rs
- examples/orders/src/lib.rs
- examples/server_integration/Cargo.lock
- examples/server_integration/client/src/lib.rs
- examples/server_interaction/src/lib.rs
- examples/todomvc/src/lib.rs
- examples/update_from_js/src/lib.rs
- examples/user_media/src/lib.rs
- examples/websocket/src/client.rs
- examples/window_events/src/lib.rs
- src/vdom.rs
- src/vdom/builder.rs
Added alternative starting code: `AppBuilder.start()`, which combines `.finish()` and `.run()`. These two are usually associated with each other. This flow's a little cleaner.
```rust
#[wasm_bindgen(start)]
pub fn render() {
seed::App::build(|_, _| Init::new(Model::default()), update, view)
.finish()
.run();
}
```
to 
```rust
#[wasm_bindgen(start)]
pub fn render() {
seed::App::build(|_, _| Init::new(Model::default()), update, view)
.start();
}
```
Are there any cases where we do something between `finish()` and `run()`? Can still do the former, but am wondering for documentation purposes.
Open to alternatives / further simplifications / renames etc. For example, what do you think about `seed::build` to start, instead of `seed::App::build`? This would be a little simpler, but hides that …
> Added `AppBuilder.start()`, combining `finish()` and `run()`

- CHANGELOG.md
- Cargo.toml
- examples/mathjax/src/lib.rs
- src/routing.rs
- src/websys_bridge.rs
There were bugs in `Url` parsing (see new and updated tests). 
I've refactored `routing.rs` to use native `web_sys::Url` for parsing and fixed some new clippy errors.
Tested with projects which uses hash routing and standard routing.
@David-OConnor What's the real purpose of function `clean_url`?
https://github.com/David-OConnor/seed/blob/8a6d60acd659fed1bb53db0dbd17ccc1826176e8/src/routing.rs#L208
> Fix - hash routing

- CHANGELOG.md
- examples/server_integration/Cargo.lock
- examples/server_integration/client/Cargo.toml
- src/util.rs
- src/websys_bridge.rs
> fix: jumping cursor

- CHANGELOG.md
- examples/animation_frame/src/lib.rs
- examples/canvas/src/lib.rs
- examples/orders/src/lib.rs
- src/lib.rs
- src/orders.rs
- src/util.rs
- src/vdom.rs
Resolves #207 
Changes
- Added method `orders.after_next_render(Option<RenderTimestampDelta>)`.
- Updated and refactored examples `animation_frame` and `canvas`.
- Refactored function `canvas`.
No breaking changes.
> after_next_render

- CHANGELOG.md
- examples/animation_frame/src/lib.rs
- examples/canvas/src/lib.rs
- examples/counter/src/lib.rs
- examples/drop/README.md
- examples/drop/src/lib.rs
- examples/mathjax/src/lib.rs
- examples/orders/src/lib.rs
- examples/server_integration/client/src/lib.rs
- examples/server_interaction/src/lib.rs
- examples/server_interaction_detailed/reports/src/lib.rs
- examples/todomvc/src/lib.rs
- examples/update_from_js/src/lib.rs
- examples/user_media/src/lib.rs
- examples/websocket/src/client.rs
- examples/window_events/src/lib.rs
- src/lib.rs
- src/orders.rs
- src/vdom.rs
- src/vdom/builder.rs
- src/vdom/builder/after_mount.rs
- src/vdom/builder/before_mount.rs
- src/vdom/builder/init.rs
Here's an implementation for the new API (#250) that I've been toying around with.
I may have gone a little crazy on the types.... I could have also combined 4 of the fields in the new `AppBuilder` struct into 2, but it might have been (even more) confusing, so I left it as is.
It should still support everything for the older version, and I haven't marked the old methods as deprecated yet.
I also haven't gotten around to converting the examples yet, but I've been up pretty much all night at this point, so I'll fix it later.
> New AppBuilderAPI

- CHANGELOG.md
- examples/server_integration/client/src/lib.rs
- src/dom_types.rs
- src/events.rs
- src/orders.rs
- src/vdom.rs
This patch alignes the public API of `MessageMapper::map_msg` with `Orders::send_msg`.
This is a breaking change.
> Rename trait fn map_message to map_msg

- src/browser/util.rs
> Fix panic when clicking on range inputs

- examples/server_interaction_detailed/src/datetime.rs
- examples/server_interaction_detailed/src/util.rs
- examples/update_from_js/src/lib.rs
- examples/websocket/src/server.rs
- src/app.rs
- src/browser/service/fetch.rs
- src/lib.rs
- src/virtual_dom/listener.rs
- src/virtual_dom/node.rs
The `must_use` lint seems a little... aggressive. Disabled it for the main repo. CI is still failing for examples. I don't want to add either this tag, or the allow to examples; maybe we can use normal `clippy` instead of `clippy::pedantic` in the examples.
> Cleaned up Clippy checks

- CHANGELOG.md
- src/virtual_dom/node/el.rs
- src/virtual_dom/patch.rs
https://github.com/seed-rs/seed/issues/325
Custom elements (like `code-block` on `seed-rs.org`) have to be recreated, we cannot manage their content directly (i.e. we can't patch them like the built-in elements).
We should try to find a better solution and write tests once there is a solid Rust wrapper for WebComponents.
Tested with `seed-rs.org` project connected to modified local Seed repository.
> Fixed custom elements patching, Added El::is_custom()

- CHANGELOG.md
- src/browser/dom/virtual_dom_bridge.rs
There was a problem with comments in mount points (when you are also using `MountType::Takeover`) or when you want to use `raw!` macro.
Bug example: https://realworld.seed-rs.org/ - see console log - `"Unexpected node type found from raw html"`. Comment that causes the error - https://github.com/seed-rs/seed-rs-realworld/blob/a72c331f1cf53d55e71445c0f00552df513e12b1/index.html#L15.
> Removed unnecessary error message for comment nodes

- src/app.rs
- src/app/builder/before_mount.rs
- src/virtual_dom/node.rs
- src/virtual_dom/node/el.rs
See commit code for explanation.
> Improve before_mount docs and do runtime debug check

- src/virtual_dom/event_handler_manager/event_handler.rs
the current implementation does require `Ms` to impl `Clone` :D
https://doc.rust-lang.org/stable/std/clone/trait.Clone.html#derivable
> impl Clone manually for EventHandler<Ms>

- src/browser/service/routing.rs
- src/browser/url.rs
fixes a small typo I found in the documentation.
Thanks for your awesome work!
> fixes typo Refenences -> References

- .github/workflows/main.yml
Note: The latest Cargo doesn't require `--force`
> Fix failing GHA pipeline

- CHANGELOG.md
- examples/orders/src/lib.rs
- examples/todomvc/src/lib.rs
- src/lib.rs
- src/shortcuts.rs
- src/virtual_dom.rs
- src/virtual_dom/update_el.rs
Resolves https://github.com/seed-rs/seed/issues/370.
Resolves https://github.com/seed-rs/seed/issues/365.
Resolves https://github.com/seed-rs/seed/issues/128.
Changelog:
- [BREAKING] `UpdateEl<T>` changed to `UpdateEl<Ms>` and `fn update(self, el: &mut T);` to `fn update_el(self, el: &mut El<Ms>);`.
- Added trait `UpdateElForIterator<Ms>`.
- Added support for all `Iterator`s, `Option`, `u32`, `i32`, `usize`, `f64` and references in element creation macros.
> UpdateEl refactor + updates

- CHANGELOG.md
- src/browser/service/routing.rs
The `use` tag can contain an `href`. It should be excluded when looking
for the closest tag for routing purposes.
Signed-off-by: Joe Grund <jgrund@whamcloud.io>
> Exclude use tag when routing

- CHANGELOG.md
- examples/server_integration/client/src/example_e.rs
- examples/subscribe/src/lib.rs
- src/app.rs
- src/app/get_element.rs
- src/app/subs.rs
- src/app/types.rs
- src/lib.rs
Changes
- Added method `App::start` (alternative to `AppBuilder`) (#376, #382).
- Added trait `GetElemnt` + included in the `prelude` (alternative to `MountPoint`, used in `AppStart`).
- Updated example `subscribe` to use `App::start`.
> App::start

- .github/workflows/main.yml
- CHANGELOG.md
- src/browser/dom/virtual_dom_bridge.rs
- src/virtual_dom/node.rs
- src/virtual_dom/node/el.rs
- src/virtual_dom/view.rs
Resolves #394 
- Removes `'static` bound on `El` and `Node`.
- Fixes failing CI.
Based on https://github.com/seed-rs/seed/pull/395.
> Remove 'static for Node and El

- .github/workflows/main.yml
- CHANGELOG.md
- examples/subscribe/src/lib.rs
- examples/tea_component/src/counter.rs
- examples/todomvc/src/lib.rs
- examples/update_from_js/src/lib.rs
- src/app.rs
- src/app/cmds.rs
- src/app/data.rs
- src/app/orders.rs
- src/app/orders/container.rs
- src/app/orders/proxy.rs
- src/app/streams.rs
- src/app/streams/window_event.rs
- src/app/sub_manager.rs
- src/browser/dom/event_handler.rs
- src/virtual_dom/el_ref.rs
- src/virtual_dom/event_handler_manager/event_handler.rs
- src/virtual_dom/event_handler_manager/listener.rs
Resolves #391 
`ev`, `orders.subscribe`, `orders.after_next_render`, etc. accept handlers which return `Msg` or `()`.
+ CI fix
> Handlers accept Msg or ()

- CHANGELOG.md
- examples/app_builder/src/lib.rs
- examples/canvas/src/lib.rs
- examples/counter_advanced/src/lib.rs
- examples/drop_zone/src/lib.rs
- examples/mathjax/src/lib.rs
- examples/orders/src/lib.rs
- examples/server_integration/client/src/lib.rs
- examples/subscribe/src/lib.rs
- examples/todomvc/src/lib.rs
- examples/user_media/src/lib.rs
- examples/websocket/src/client.rs
- src/app.rs
- src/app/builder.rs
- src/app/builder/after_mount.rs
- src/app/builder/init.rs
- src/app/cfg.rs
- src/app/orders.rs
- src/app/orders/container.rs
- src/app/orders/proxy.rs
- src/app/types.rs
- src/lib.rs
- src/shortcuts.rs
- src/virtual_dom/el_ref.rs
- src/virtual_dom/node.rs
- src/virtual_dom/node/into_nodes.rs
- src/virtual_dom/patch.rs
- src/virtual_dom/view.rs
Changes
- [deprecated] `View` is deprecated in favor of `IntoNodes`.
- [BREAKING] `View` isn't implemented for `El` and `Vec<El>`.
- [BREAKING] `Node::add_listener` renamed to `add_event_handler`.
Motivation
- There were some questions about `View` - what is it and when to use it. `IntoNodes` is more expressive and already in the code => it makes `View` redundant.
- `add_listener` was forgotten during renaming `listeners` to `event_handlers`.
> IntoNodes instead of View

- CHANGELOG.md
- examples/todomvc/src/lib.rs
- src/app/cmds.rs
- src/app/orders.rs
- src/app/orders/container.rs
- src/app/orders/proxy.rs
- src/app/streams.rs
- src/app/streams/window_event.rs
- src/browser/dom/event_handler.rs
- src/lib.rs
Handlers accept Msg, **Option\<Msg\>** and ().
Motivation:
See copy-pasted code from updated `todomvc` example below:
```rust
keyboard_ev(Ev::KeyDown, |keyboard_event| {
IF!(keyboard_event.key_code() == ENTER_KEY => Msg::CreateNewTodo)
}),
...
keyboard_ev(Ev::KeyDown, |keyboard_event| {
match keyboard_event.key_code() {
ENTER_KEY => Some(Msg::SaveEditingTodo),
ESC_KEY => Some(Msg::CancelTodoEdit),
_ => None,
}
}),
```
> Handlers accept Msg, Option<Msg> and ()

- src/browser/fetch/header.rs
So user can use String and to mirror other header methods signatures.
> feat(fetch): Change `bearer` type to `Into<Cow>`

- CHANGELOG.md
- src/browser/dom/virtual_dom_bridge.rs
Resolves #405 
We mirror `value` and `checked` attributes to properties while we are adding attributes, but we forgot to do the same while removing attributes.
> fix: Reset checked and value on attribute remove

- src/app.rs
- src/browser/dom.rs
- src/virtual_dom.rs
- src/virtual_dom/event_handler_manager/listener.rs
- src/virtual_dom/mailbox.rs
Achieved by allowing Mailbox to accept `Option<Msg>`.
this allows 'App::rerender_vdom()' to be directly called if the mailbox is processing `None`.
> re-render on EventHandler callback even if EventHandler's callback returns `()` or `None`.

- src/app/orders.rs
I've noticed some redundant parentheses in some no_run annotated doctests, so I fixed them.
Feel free to close this issue if the changes are not needed.
Best,
ambiso
> Fix extraneous parentheses

- examples/server_interaction/src/lib.rs
- src/browser/fetch/response.rs
Changes
- Added `Response::bytes`.
- `Response` methods `text`, `json` and `bytes` don't consume `self`.
> feat: Response::bytes

- src/browser/fetch/response.rs
Fixes #427 
Change from `Uint8Array::from` to `Uint8Array::new`.
I added a closure in order to borrow the ArrayBuffer, I don't know whether that is avoidable or desirable to avoid.
> Fix bytes interface of Response

- CHANGELOG.md
- src/virtual_dom/patch/patch_gen.rs
Disabling patch for custom elements was introduced as a fix for #325 #328.
I propose another solution using an observer (see https://github.com/seed-rs/seed-rs.org/pull/46).
This will allow the use of custom elements with an internal state.
Solves #364
> Allow to patch custom elements

- src/browser/web_socket/builder.rs
- src/shortcuts.rs
- src/virtual_dom/patch/patch_gen.rs
Clippy showed up a pair of redundant visibilites ([explination](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pub_crate)), and a [missing_const_for_fn](https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn)
> Clean up clippy lints. (nightly)

- CHANGELOG.md
- examples/pages/index.html
- examples/url/index.html
- src/app.rs
- src/app/orders.rs
`<base href="/base/path/">` - there should be a trailing slash because browsers can't route static files properly without it. However Seed didn't expect the trailing slash and it was breaking base path handling.
> fix: Base path with a trailing slash

- CHANGELOG.md
- src/shortcuts.rs
When the app in [quickstart-webpack](https://github.com/seed-rs/seed-quickstart-webpack) uses Seed 0.7.0 and `C!` (instead of `class!`), then the WASM file size (in debug mode) has 7.58 MB and fails during the start with `CompileError: wasm validation error: at offset 26669: too many locals` (build is also pretty slow). 
Both new helper functions introduced in the PR - `_fill_all_classes` and `_all_classes_to_attrs` - reduce the WASM size by +/-2 MB so with this PR the result size is 3.15 MB.
I've resolved this issue by intuition, but I don't really know why this happens, how to prevent it and if we can define a general rule - e.g. "macros should be as small as possible".
Opinions? (cc @rebo, @akhilman, @flosse, @TatriX)
> fix: C macro memory issue

- README.md
I used the commit sha instead of the `master` name to make the link permanent. So we can move or rename the files on the master.
> Use commit sha instead of 'master' as url logo (permalink)

- examples/pages/README.md
Expanded README to more fully explain the purpose and function of the pages example.
> doc(README): expand on pages example description

- examples/pages_keep_state/README.md
Expanded README to more fully explain the purpose and function of the pages_keep_state example.
> doc(README): expand on pages_keep_state example description

- CHANGELOG.md
- Cargo.toml
- examples/websocket/Cargo.toml
- examples/websocket/src/client.rs
- examples/websocket/src/server.rs
- src/browser/web_socket.rs
- src/browser/web_socket/message.rs
This PR replaces the `Blob:array_buffer` usage with the FileReader. This change fixes #470.
This is my first PR to seed, and the first time that I had anything to do with wasm_bindgen so I would really appreciate a review.
> Replace `Blob::array_buffer` with `FileReader`

- CHANGELOG.md
- src/app.rs
- src/browser/service/routing.rs
This PR removes `hashchange` listener because it was causing double `UrlChanged` firing (one from `hashchange` listener and one from `popstate` listener). 
I haven't found a case where `hashchange` is fired and `popstate` not.
> Fix: Double UrlChanged firing (setup_hashchange_listener removed)

- src/virtual_dom/el_ref.rs
should close #[493]. The thought occurred to me to reference the example-code it's based on. If that's to be done, it's for another PR
> docs: Remove use of AfterMount in ElRef example

- src/app/orders.rs
Change is relatively trivial and self-explanatory. There might also be a need to add a checklist item to stabilisation if there isn't already something in place to ensure this doc comment is removed as appropriate. I'm not up to date on that, though.
> Refer run-time panic issue fix in documentation.

- examples/fetch/src/post.rs
Hello guys !
One of the joy I have with `seed` is that I rediscover pure html :+1: 
Anyway, yesterday I realized that the submit event on a form and a button are not the same and that our nice example from fetch could be improved.
It is simpler and also better to use the submit even from the form since it will also pop only if the form is valid :)
PS: is it fine to have a comma inside `button!["Submit",]` or is there a standard for that ?
I can remove it if needed
> fix: use submit event on form instead and simplify code

- CHANGELOG.md
- src/browser/fetch/response.rs
the underlying web_sys::Response implements debug, so may as well take advantage of it.
> Annotate fetch::Response with derive Debug

- CHANGELOG.md
- examples/url/src/lib.rs
- examples/websocket/src/client.rs
- src/app/orders.rs
- src/app/orders/container.rs
- src/app/orders/proxy.rs
- src/lib.rs
> Orders::request_url + msg_sender

- CHANGELOG.md
- src/browser/service/routing.rs
This PR prevents seed from intercepting links with a download attributes
```html
<a download="filename.ext" href="/files/filename.ext">filename.ext</a>
```
> prevent system from intercepting links with a download attribute

- CHANGELOG.md
- Cargo.toml
- examples/README.md
- examples/drop_zone/Cargo.toml
- examples/e2e_encryption/client/Cargo.toml
- examples/record_screen/Cargo.toml
- examples/record_screen/Makefile.toml
- examples/record_screen/README.md
- examples/record_screen/index.html
- examples/record_screen/src/lib.rs
- examples/server_integration/client/Cargo.toml
- examples/service_worker/Cargo.toml
- examples/tests/Cargo.toml
- examples/update_from_js/Cargo.toml
- examples/user_media/Cargo.toml
- examples/websocket/Cargo.toml
Added new example `record_screen`.
Merge once the new `wasm-bindgen` version is released with the feature flag `DisplayMediaStreamConstraints`. Probably version `>= 0.2.70`. And don't forget to remove the `[patch.crates-io]` block and update all related deps in `Cargo.toml`s.
> examples: record_screen

- README.md
Mail from _Discourse Team_:
> I’m writing to you about your free Discourse site on seed.discourse.group. It has seen no activity for a while and as mentioned in our FAQs here, having an active community is required to continue participating in the program.
Chat is much more popular. I'll disable the forum.
> docs: remove links to forum; remove "rapid" development

- CHANGELOG.md
- Cargo.toml
- src/app.rs
- src/lib.rs
Adds a `panic-hook` feature, enabled by default, to be able to conditionally disable the panic hook set in `App::start` This is necessary to be able to use a custom panic hook that will also catch errors that might occur during `App::start`.
> Hide `console_error_panic_hook` behind `panic-hook` feature

- src/app.rs
When user code panics you can often see
```
panicked at 'already mutably borrowed: BorrowError', ./seed/src/app.rs:344:56
```
As unwinding is not yet implemented for WASM there is no way we can
recover from the panic. In other words if `view` or `update` panics,
model will remain borrowed and always lead to panic in seed.
That error is confusing for the user. It's also unwanted when one
wants to use custom panic hook.
This PR prevents `BorrowError` by checking for already happening panic.
> fix: Don't rerender or process effects queue when there is a panic

- CHANGELOG.md
- Cargo.toml
- examples/el_key/Cargo.toml
- examples/markdown/Cargo.toml
- src/virtual_dom/node.rs
- src/virtual_dom/node/el.rs
Just to lighten the payload a little. I've probably missed something though, and if so just let me know.
> refactor: hide markdown functionality behind optional feature

- examples/animation/src/lib.rs
- examples/canvas/src/lib.rs
- examples/component_builder/src/button.rs
- examples/component_builder/src/lib.rs
- examples/counters/src/lib.rs
- examples/custom_elements/src/lib.rs
- examples/el_key/src/lib.rs
- examples/resize_observer/src/lib.rs
- examples/rust_from_js/src/lib.rs
- examples/tea_component/src/counter.rs
- examples/tea_component/src/lib.rs
As suggested in #584.
`Clone` is actually not needed on `Msg` because of the event handler, but because clippy is being a bit anal. So to reduce confusion I've removed the derive and disabled the clippy warning instead. (edit: also done for all other examples now)
I've also simplified the event handler a bit by removing the `MouseEvent` argument, partly because I think it's good design in general to not expose unnecessary implementation details, but also partly because it illustrates that `Msg`s must be passed in as a closure even if it doesn't take any arguments, unless it implements `Clone`.
> refactor(examples/component_builder): declone Msg and simplify click handler

- CHANGELOG.md
- Cargo.toml
- examples/canvas/src/lib.rs
- src/browser/dom/cast.rs
- src/browser/dom/event_handler.rs
- src/lib.rs
- add helpers
- `wheel_ev` - see `keyboard_ev`
- `to_wheel_event` - see `to_keyboard_event`
- use `wheel_ev` in `canvas` example
- scrolling the mouse wheel while the mouse pointer is within the canvas zooms the rectangle
> Add helpers for wheel event

- CHANGELOG.md
- examples/auth/src/lib.rs
- examples/e2e_encryption/client/src/lib.rs
- examples/i18n/src/i18n.rs
- examples/service_worker/src/lib.rs
- examples/websocket/src/client.rs
- src/browser/web_socket/message.rs
- src/dom_entity_names/attributes/attribute_names.rs
This PR adds a `Role` variant for the giant `At` enum, so that the `role` attribute can be used like so:
```html
<nav role="navigation"></nav>
```
> Add `At::Role`

- CHANGELOG.md
- src/browser/util.rs
This addresses a problem we encountered with number inputs in Firefox, where `HtmlInputElement.value` will only return a valid number. or the empty string, instead of the actual contents of the input. This causes two problems in typical use, 1) it clears the input if the user enters an invalid character, and 2) it's not possible to enter the decimal point key-by-key since entering e.g. `12.` will have `value` return `12`, thereby deleting the decimal point.
The workaround implemented here is to simply not update the DOM if `value` seems unchanged. In the problematic case above it has, of course, and this will cause the input to become out of sync with the model. But the root of the problem is that it already is, and there seems to be no way to get the actual contents of the input. So it …
> fix(vdom): don't update value property if it hasn't changed

- CHANGELOG.md
- Cargo.toml
- src/browser/fetch.rs
- src/browser/fetch/form_data.rs
- src/browser/fetch/request.rs
Provides a very simplified and incomplete interface to the `FormData` Web API in order to support multipart requests for fetch with some convenience.
> Basic FormData interface for multipart support in fetch

- CHANGELOG.md
- examples/custom_elements/index.html
- examples/custom_elements/src/lib.rs
- examples/custom_elements/src/sl_input.rs
I can imagine we can implement a helper macro like `make_custom_element!("sl-input")` later. Maybe also some `Reflect` helpers would be nice.
> example: sl_inpuit added to custom_elements

- CHANGELOG.md
- examples/server_integration/client/src/example_e.rs
- src/browser/fetch/request.rs
Since `RequestInit::body` actually takes a `&JsValue`, we can have `Request::body` take a reference too, and store it in a `Cow` internally, which helps with sharing data in interop-heavy code that assumes JS idioms and GC'd values.
This is a breaking change, but a minor one I think. Alternatively we could add a separate `body_ref` function instead.
> fix(fetch): changed Request.body to take its argument by reference

- README.md
- examples/README.md
- highlight features in the first paragraph such as idiomatic templating and built-in state management
- improved wording throughout the entire README.md
- lightened the tone sometimes
- improved flow where possible
- changed the headings (e.g. ## to ### sometimes) to look nice and consistent
- removed dead link to About page
- remove mention of Seeder
- add mention of trunk
- add quickstart example right in the root readme
Remove some text such as how to run an example and the Counter component example.
I think it's better for people to use the README to learn about the
project. Those details are on the website docs and Examples README.
> Improve README, highlight Seed features

- Cargo.toml
- examples/intersection_observer/Cargo.toml
- examples/intersection_observer/Makefile.toml
- examples/intersection_observer/README.md
- examples/intersection_observer/index.html
- examples/intersection_observer/public/index.css
- examples/intersection_observer/src/lib.rs
- added Makefile and works with `cargo-make`
- added newline to the end of `index.html` (it's not displayed on GitHub but you can see it when you click "Edit file")
- removed printing with Debug where not needed
- formatted with `rustfmt` (forgot last time!)
This PR is for Issue #612 and replaces PR #613.
The reason for tis new PR is me being bad at `git`. I deleted my fork and re-forked.
I wasn't sure how to get the CSS to work with both `trunk` and `cargo-make`.
> Intersection Observer example (again)

- CHANGELOG.md
- src/browser/fetch/response.rs
Resolves #616
This PR introduces a new enum variant for `FetchError` that contains the response status together with the JSON response returned from the server.
Initially, I wanted to change the `check_status()` method to try to return the new variant first, and in case of JSON parse error just return the regular `StatusError`, but it would require changing the method to `async` which would be a breaking change. Therefore I decided to add another method.
Here's how it looks when you `log!()` such error:  
```
DetailedStatusError(
Status {
code: 500,
text: "Internal Server Error",
category: ServerError,
},
Object({
"details": String("cannot connect to the database",),
}),
)
```
> Return response with details from the server on error

- README.md
It was redirecting to:
https://github.com/seed-rs/seed#232
but I think what was meant to be is this:
https://github.com/seed-rs/seed/issues/232
> Fix Issue#232 link in Readme-Why not Seed section

- CHANGELOG.md
- src/virtual_dom/node/into_nodes.rs
This replaces the specific `impl`s of `IntoNodes` for `Option<Node<Ms>>` and `Option<Vec<Node<Ms>>` with a blanket implementation for `Option<T> where T: IntoNodes`. This isn't just for convenience, as it also solves the problem of not being able to implement `IntoNodes<Ms>` for `Option<T>` if `T` does not include `Ms` as a type parameter, since that violates the orphan rule (`E0210``).
> feat(virtual-dom): blanket impl of IntoNodes for Option

- src/browser/url.rs
> Fix typo in url module docs

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/app.rs
- src/app/orders.rs
- src/browser.rs
- src/browser/fetch.rs
- src/browser/fetch/form_data.rs
- src/browser/fetch/request.rs
- src/browser/fetch/response.rs
- src/browser/json.rs
- src/browser/json/serde_json.rs
- src/browser/json/swb.rs
- src/browser/service.rs
- src/browser/service/routing.rs
- src/browser/url.rs
- src/browser/web_socket.rs
- src/browser/web_socket/message.rs
- src/browser/web_storage.rs
- src/lib.rs
This PR introduces two features: `serde-json` and `swb` and it makes `serde-json` as default again. If you like you use `serde-wasm-bindgen` instead, just enable the feature `swb`.
> serde json and swb
