seed-rs/seed

src/dom_types.rs, src/shortcuts.rs, src/websys_bridge.rs
It would be cool to be able to render SVG elements as well.
Here is a first draft as a base for a discusstion :)
=> WIP: add basic SVG rendering support

Cargo.toml, examples/websocket/Cargo.toml, examples/websocket/build.sh, examples/websocket/index.html, examples/websocket/src/client.rs, examples/websocket/src/json.rs, examples/websocket/src/server.rs
This is a first try to solve #8.
It's incomplete at the moment. I'm very happy to receive some feedback :)
=> WIP: add websocket example

examples/websocket/index.html, examples/websocket/src/client.rs, examples/websocket/src/server.rs, src/vdom.rs
This is a quick and dirty approach to be able to send messages from the client to the server.
Do you have an idea how to do it better?
=> Ws with listener

src/websys_bridge.rs
This now works with:
```
El::from_html("<div>
<p>Example: This is a <strong>sentence</strong> of text and it also has some <em>italicized text</em> too.</p>
<p>This is another paragraph.</p>
</div>")
```
Resulting in:
However, it works by attaching the ```<span>``` raw_html to the parent nodes inner_html. The ```<span>``` children (is there a way to create them?) are also attached directly to the parent. 
Is this what you had in mind?
=> A new solution to the raw_html problem, append to parents inner_html

src/vdom.rs
I have found it useful to be able to debug-print my `Msg`s, but they often contain the `App`, so I think it would be useful to have a very basic `Debug` impl on it.
=> impl Debug for App

src/dom_types.rs
In order to keep the "value" property set by the user in sync with the render we get the value property and use set_value right after the users event handler.
For the case when the input field was invalidated (such as when the user typed a letter on a number input) the value property is set to empty.
When this happens the value is set as the default_value. This works because when the value is set using set_value the default_value is also set, but it doesn't get cleared when the input is invalidated.
=> Sync Model and Render on input value update by user

src/dom_types.rs
This fixes the broken file input. Also, now we only call set_value when the default_value (which is the one set by the seed user when setting the value in the html) is different from the actual value.
This allows numeric inputs with decimal places. 
Before, when the user typed the decimal separator the seed user callback would get the same value as before (without the decimal separator). 
With the same input, the html value property would be set to the same value. Then, even though the default value and value had the same value seed would call set_value overwriting the decimal separator. 
I also tried to document this part of the code better.
=> Fix file input broken, and only call set_value when needed

src/vdom.rs
=> Add test for empty->non-empty transition. (Currently fails)

src/vdom.rs
=> Fix empty insertion position

src/dom_types.rs, src/vdom.rs
I *think* commit 15fffb8 here improves performance noticeably for updates with lots of elements where most of the elements don't change at all, but my testing isn't too scientific, so I'm not entirely sure. 
btw, would you mind running cargo fmt?
=> Delay websys el creation

examples/todomvc/src/lib.rs, src/routing.rs, src/vdom.rs
The change to return the Promise out of update is possibly less performant.
=> Test promises

src/dom_types.rs
Hello, I followed what was done for the "keydown" event, although I haven't looked precisely at what it does yet, but well, _seems to work ™_.
Please tell me if it needs extra work or tests.
=> Add keyup event

src/vdom.rs
Fixes #40
This patch allows direct mounting of an element, which is useful
when you don't know the mount id ahead of time.
Signed-off-by: Joe Grund <jgrund@whamcloud.io>
=> Allow mounting elements

src/fetch.rs, src/lib.rs, src/routing.rs, src/shortcuts.rs, src/storage.rs, src/vdom.rs, src/websys_bridge.rs
No promises that this got every single one of them, but this PR aims to improve the markdown link formatting in rustdoc comments.
=> Rustdoc Improvements

examples/counter/src/lib.rs, src/dom_types.rs, src/lib.rs, src/vdom.rs, src/websys_bridge.rs
#88 
Note: I've removed unnecessary changes, but I can't build it because of it, so pls try it before merge (I don't know if tests on CI are setuped).
=> feat: view returns El or Els

examples/update_from_js/Makefile.toml
Release tasks for example `update_from_js`
=> feat: example update_from_js - add release tasks

src/dom_types.rs
Resolves #101 
Questions:
1. Do you want to add some comments to that code?
2. I think we don't need to remove duplicated classes during merging, am I right?
Note for the future: We can probably use a faster hasher in HashMaps.
=> 101-merge-classes

src/dom_types.rs, src/vdom.rs
=> 102-proposal-mounting

CHANGELOG.md, src/util.rs
Just some typos and copy-paste mistakes.
#105
=> 105-proposal-debugging-minor-fixes

src/vdom.rs
#81 
It seems that wasm-pack uses its own panic hook, so we can fix it with `console_error_panic_hook::set_once();`. This call doesn't try to change panic hook while the thread is panicking, because wasm-pack already hooked panics.
I've also moved it from `run` method into `build` so it's hooked sooner.
If you think it's possible to init Application without call `build(..)`, we can add `console_error_panic_hook::set_once()` to other places.
=> 81-update-promises-fails

Cargo.toml, examples/websocket/src/client.rs, src/dom_types.rs
#128 
Changes:
- deleted unnecessary comment
- impl UpdateEl for iter::Map
- implementation tested in websocket client
=> 128-updateEl-for-iter-Map

src/shortcuts.rs
=> 140-macros-raw-and-md

examples/todomvc/src/lib.rs, src/lib.rs, src/routing.rs, src/vdom.rs
This PR resolves proposal part in #139.
=> 139-owned-url

src/dom_types.rs
=> Implement MessageMapper for Listener

src/events.rs
sorry it took so long, had a big day yesterday and had to learn how to use `git rebase` to squash the commit correctly
Fixes #152
=> Remove private(?) impl of map_message for Listener [Fixes #152]

src/util.rs, src/vdom.rs
=> doc: add hint to seed::update that there is App::update

examples/window_events/src/lib.rs, src/dom_types.rs, src/fetch.rs
A few smaller non-braking changes
=> add missing `pub`s in fetch.rs, tests for El's methods, minor refactors

src/dom_types.rs
Signed-off-by: Joe Grund <jgrund@whamcloud.io>
=> Implement MessageMapper trait for LifecycleHooks

src/lib.rs, src/routing.rs, src/shortcuts.rs, src/util.rs
https://github.com/David-OConnor/seed/issues/163
=> Child link listeners

src/dom_types.rs
Signed-off-by: Joe Grund <jgrund@whamcloud.io>
=> Add method to add listener to el.

src/dom_types.rs, src/shortcuts.rs, src/vdom.rs
=> Tag::Placeholder, allow unused_mut

Makefile.toml, README.md, examples/animation_frame/index.html, examples/animation_frame/src/lib.rs, examples/counter/index.html, examples/counter/src/lib.rs, examples/mathjax/index.html, examples/mathjax/src/lib.rs, examples/orders/index.html, examples/orders/src/lib.rs, examples/server_integration/Makefile.toml, examples/server_integration/client/index.html, examples/server_integration/client/src/lib.rs, examples/server_interaction/index.html, examples/server_interaction/src/lib.rs, examples/server_interaction_detailed/Makefile.toml, examples/server_interaction_detailed/reports/Makefile.toml, examples/todomvc/index.html, examples/todomvc/src/lib.rs, examples/update_from_js/index.html, examples/update_from_js/src/lib.rs, examples/websocket/Makefile.toml, examples/websocket/index.html, examples/websocket/src/client.rs, examples/window_events/index.html, examples/window_events/src/lib.rs
=> wasm-pack --target web

src/dom_types.rs, src/events.rs, src/fetch.rs, src/gloo_timers/callback.rs, src/gloo_timers/future.rs, src/lib.rs, src/routing.rs, src/util.rs, src/vdom.rs
Lack of `dyn` has started giving warnings on nightly Rust
=> Dyn trait objects

.travis.yml, README.md, examples/counter/src/lib.rs, examples/mathjax/index.html, examples/mathjax/public/math-tex-controller.js, examples/mathjax/public/math-tex.js, examples/mathjax/src/lib.rs, src/fetch.rs
Refactored `mathjax` example to use custom element.
@David-OConnor rebase/merge it once PR https://github.com/David-OConnor/seed/pull/201 is rebased on `master`
=> mathjax - custom element

examples/server_integration/client/src/example_e.rs, examples/window_events/src/lib.rs, src/dom_types.rs
Fixes issue #179 
Tested that examples and tests still compiles.
=> Make chainable methods on El and Node more convenient

src/lib.rs, src/vdom.rs
Needed to make the AppBuilder type public for its documentation to be
generated.
=> Improve documentation for AppBuilder

Makefile.toml, RELEASE_CHECKLIST.md
=> feat(tasks): populate_all

CHANGELOG.md, README.md, examples/animation_frame/src/lib.rs, examples/counter/src/lib.rs, examples/mathjax/src/lib.rs, examples/orders/src/lib.rs, examples/server_integration/client/src/example_c.rs, examples/server_integration/client/src/example_d.rs, examples/server_integration/client/src/example_e.rs, examples/server_integration/client/src/lib.rs, examples/server_interaction/src/lib.rs, examples/todomvc/src/lib.rs, examples/update_from_js/src/lib.rs, examples/websocket/src/client.rs, examples/window_events/src/lib.rs, src/dom_types.rs, src/lib.rs, src/vdom.rs
https://github.com/David-OConnor/seed/issues/224
Tests currently broken.
=> Init routing

examples/drop/src/lib.rs
Just fix for conflict between last two merged PRs.
=> fix(examples) - drop example - Init<Model>

src/patch.rs, src/vdom.rs
Resolves a bug, where if the top level `view` function returns a `Vec` of `Node`s and you navigate away to a different page with a different number of top level elements, weird things happen.
Weird things meaning that routing and rerendering/diffing the vdom adds extra elements to the mount point.
=> Factor out duplicate logic in `vdom::rerender_vdom` and `path::patch_el`

CHANGELOG.md, examples/counter/src/lib.rs, src/shortcuts.rs, src/websys_bridge.rs
https://github.com/David-OConnor/seed/issues/236, take 2
Need to figure out how to populate the tags to intercept. Could just dump them in with the current, or somehow use the macro tags.
=> Intercept raw html SVG elements, and set their namespace

src/patch.rs, src/vdom.rs
Shoud resolve https://github.com/David-OConnor/seed/issues/193.
=> fix(virtual_dom): Fix diff

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, examples/server_integration/Cargo.lock, src/lib.rs
=> Release 0.4.2

examples/README.md, examples/animation_frame/src/lib.rs, examples/canvas/src/lib.rs, examples/counter/src/lib.rs, examples/drop/src/lib.rs, examples/homepage/README.md, examples/mathjax/src/lib.rs, examples/orders/src/lib.rs, examples/update_from_js/src/lib.rs, examples/user_media/src/lib.rs, examples/websocket/src/client.rs
I'm going through the examples to better learn the framework. When there are more then 5 examples it's nice to have an overview of all of them, even better with some order of increasing complexity.
=> Docs for examples

src/browser/dom/event_handler.rs, src/virtual_dom/listener.rs, src/virtual_dom/node.rs, src/virtual_dom/node/el.rs
Solve https://github.com/seed-rs/seed/issues/316
=> impl `Clone` for `Listener` and `EventHandler`

CHANGELOG.md, examples/server_integration/Cargo.lock, examples/todomvc/src/lib.rs, src/virtual_dom/update_el.rs
https://github.com/seed-rs/seed/issues/128
See code for changes.
=> Implemented UpdateEl for Filter and FilterMap

README.md
Hello, 
Simple link fix on the README file.
Cheers
=> Fixes todo mvc link on README

src/dom_entity_names/events/event_names.rs
https://github.com/seed-rs/seed/issues/358
=> Added visibility change event

CHANGELOG.md, src/dom_entity_names/attributes/attribute_names.rs
https://github.com/seed-rs/seed/issues/355
=> Added aria attrs

src/virtual_dom/el_ref.rs
Resolves https://github.com/seed-rs/seed/issues/387
=> Debug for ElRef

examples/graphql/Cargo.toml, examples/graphql/graphql/queries.graphql, examples/graphql/graphql/schema.graphql, examples/graphql/src/lib.rs
- Continents and countries sorting.
- Adapted to updated data source (https://github.com/trevorblades/countries/pull/16, https://github.com/trevorblades/countries/pull/15).
- Fixed country scrollbar.
=> GraphQL example upd

CHANGELOG.md, examples/drop_zone/Cargo.toml, examples/drop_zone/src/lib.rs
Updated example `drop_zone` to read and display contents of dropped files.
=> examples: drop_zone update - read text

Cargo.toml, examples/url/src/lib.rs, src/browser.rs, src/browser/url.rs, src/lib.rs
- Automatic `Url` decoding.
- `UrlSearch` aka parsed `search`.
- Updated `url` example.
=> Url decoding + UrlSearch

CHANGELOG.md, examples/auth/src/lib.rs, examples/pages/src/lib.rs, examples/pages_hash_routing/src/lib.rs, examples/pages_keep_state/src/lib.rs, src/browser/fetch/request.rs, src/browser/service/fetch.rs, src/virtual_dom/event_handler_manager.rs
=> Request::bytes

BACKERS.md
BACKERS.md update.
@km-tr and @sabine - please choose your nick or write me your name so I can replace the placeholders in the list, thank you!
=> docs: BACKERS.md

.github/workflows/main.yml, BACKERS.md, Cargo.toml
@craigmayhew Thank you for the support! 
Can I merge it?
=> docs: BACKER.md

src/dom_entity_names/events/event_names.rs
Hello :)
First PR here, so happy !
I read CONTRIBUTING.md and it says to look at the todo. My jetbrain likes todo stuff, so I found something to start with.
In this PR I will finish to list the events from there https://developer.mozilla.org/en-US/docs/Web/Events
++ =>
Thank you for your inputs !
=> Added missing events

BACKERS.md
@arn-the-long-beard Thank you very much! 
Do you want to change the name or link?
=> docs: BACKERS.md updated

CHANGELOG.md, src/browser/service/routing.rs
Fixes https://github.com/seed-rs/seed/issues/527
=> fix: Link handling - ignore non-a elements

CHANGELOG.md, Cargo.toml, examples/README.md, examples/resize_observer/Cargo.toml, examples/resize_observer/Makefile.toml, examples/resize_observer/README.md, examples/resize_observer/index.html, examples/resize_observer/public/observe_element_size.js, examples/resize_observer/src/lib.rs
Resolves https://github.com/seed-rs/seed/issues/533
=> examples: resize_observer

src/browser/dom/virtual_dom_bridge.rs
=> fix: Attribute order

examples/websocket/README.md
old link is now dead/malicious.
=> examples: point ws-rs link to repository

BACKERS.md, examples/custom_elements/src/feather_icon.rs, examples/server_integration/client/src/example_e.rs, src/browser/fetch/status.rs, src/browser/service/fetch.rs, src/browser/url.rs, src/virtual_dom/node.rs, src/virtual_dom/patch/patch_gen.rs
- Seed adapted to Rust 1.47.0 (refactor)
- `Ke Ding` added to `BACKERS.md` (thanks @DingDean!)
=> Rust 1.47.0 ; backers update

src/browser/fetch.rs
Fixes the documentation as explained in https://github.com/seed-rs/seed/issues/552.
=> Fixes Documentation Error (See Issue 552)

README.md
=> #302 How to install cargo-make

README.md
Mention BACKERS.md, DigitalOcean, Netlify
=> Add "supported by" section in README

examples/service_worker/Cargo.toml
Hey guys. Here is a tiny fix for `service_worker`
=> doc: updated tokio dependency in service_worker example

BACKERS.md
=> BACKERS.md update - Devin Alvaro

examples/todomvc/src/lib.rs
Ref: https://github.com/MartinKavik/seed-app-todomvc/pull/3
=> Consider title trim and empty case

CHANGELOG.md, src/browser/fetch/response.rs
=> feat(fetch): Add Response.blob

CHANGELOG.md, Cargo.toml, examples/README.md, examples/counters/Cargo.toml, examples/counters/Makefile.toml, examples/counters/README.md, examples/counters/index.html, examples/counters/src/counter.rs, examples/counters/src/lib.rs
How to use multiple "components".
=> examples: counters

CHANGELOG.md, src/virtual_dom/values.rs
I've found myself needing this a few times. Particularly with custom elements.
=> feat(attrs): implemented AsAtValue for Option<T>

CHANGELOG.md, src/lib.rs, src/shortcuts.rs, src/virtual_dom/node.rs, src/virtual_dom/node/el.rs
Fixes https://github.com/seed-rs/seed/issues/589
=> raw_svg! + namespace in El/Node::from_html

CHANGELOG.md, examples/tests/src/lib.rs, src/browser/fetch/header.rs, src/browser/fetch/response.rs
This PR adds a few methods and trait instances involving headers.
=> `Response::headers`

Cargo.lock, Cargo.toml, examples/e2e_encryption/Cargo.lock, examples/server_integration/Cargo.lock, examples/server_integration/client/src/example_e.rs, src/browser/fetch/form_data.rs, src/browser/web_socket.rs, src/browser/web_storage.rs, tests/json.rs
~~I would love it if there were a better way to canonically turn a `JsValue` into a `String`.~~ There is!
Closes #619
=> Fix string encoding issue

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/README.md, examples/page_trait/Cargo.toml, examples/page_trait/Makefile.toml, examples/page_trait/README.md, examples/page_trait/index.html, examples/page_trait/src/lib.rs, examples/page_trait/src/page.rs, examples/page_trait/src/page/create_page.rs, examples/page_trait/src/page/my_page.rs, examples/page_trait/src/page/my_page_2.rs, examples/page_trait/src/page/page_trait.rs
=> examples: page_trait

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/on_insert/Cargo.toml, examples/on_insert/Makefile.toml, examples/on_insert/README.md, examples/on_insert/index.html, examples/on_insert/src/lib.rs, src/browser/dom/virtual_dom_bridge.rs, src/lib.rs, src/virtual_dom.rs, src/virtual_dom/node.rs, src/virtual_dom/node/el.rs, src/virtual_dom/patch.rs, src/virtual_dom/update_el.rs
=> Feat/virtual com/on insert

CHANGELOG.md, src/browser/fetch.rs
=> Fix: make fetch::JsonError public
